### PR TITLE
Add separate sensitivity for 1st vs 3rd person

### PR DESCRIPTION
**Pull request by haktical**
Added variables + ini for 3rd person sensitivity.
Added new 5-argument version of /zealcam to set 1st and 3rd person sensitivities separately.
Adjusted previous 3-argument /zealcam to set both 1st and 3rd person sensitivities.
Updated camera_mods to check for zeal_cam to apply 3rd person sensitivity instead.
3rd person sensitivies default to the same as 1st person.

### CODE REVIEW

**Review by iamclint — CHANGES_REQUESTED** [review]
like 282 if statement on camera_mods.cpp changes sensitivity_x and sensitivity_y but after the if the statement at line 290 sensitivity is overwritten making these 3rd variables unused. please modify

**Comment by haktical** [comment]
Fixed. I had added it originally, but forgot to re-add the calc when I updated to the most recent version.

**Review by iamclint — CHANGES_REQUESTED** [review]
if (!ini->exists("Zeal", "MouseSensitivityX3rd"))
        ini->setValue<float>("Zeal", "MouseSensitivityX3rd", user_sensitivity_x);
    if (!ini->exists("Zeal", "MouseSensitivityY3rd"))
        ini->setValue<float>("Zeal", "MouseSensitivityY3rd", user_sensitivity_y);
        
can you move these inits and 2 new variable reads below the original.

This way the user_sensitivity_x and y are set from the ini before these new variables are initialized which would make it backwards compatible for current users by putting their current values in x and y 3rd cam on first run. If that doesn't make sense let me know.

**Comment by haktical** [comment]
Updated.
- Moved 3rd person variables to below pre-existing.
- Changed the set for 3rd person variables if not initialized to use the 1st person values.

**Review by iamclint — APPROVED** [review]

**Pull request merged**
