### PR TITLE
Added NameplateColors to Zeal

### PR DESCRIPTION
**Pull request by adonislive**
Feature adds better visibility to Nameplate Colors for Raids, Guilds, Groups, AFK, and LD situations. A player on Discord had requested I submit what I had done so far.

Two ways to use feature currently:
1. /nameplatecolors command to toggle feature
2. bind key available to toggle feature

Feature adds itself the the eqclient.ini and remembers the bool setting that player sets for next gaming session.

When feature is off the client has normal hardcoded Nameplate Colors.

When feature is on the client has the following Nameplate Colors for better visibility in game:

Raid Members:  Black
Guild Members: Light Green
Group Members: Greenish Blue
Away from Keyboard-AFK:  Orange
Linkdead-LD:  Red

Open to future enhancements, mods, and feedback.

### CODE REVIEW

**Comment by iamclint** [comment]
/* 0x0048 */ Zeal::EqStructures::_EQARGBCOLOR Color;

can you change this to just EQARGBCOLOR without the namespaces, 

Side note  EQARGBCOLOR is the same thing as D3DCOLOR

**Comment by adonislive** [comment]
Sure thing. Can change it to EQARGCOLOR. Also can get started on adding the options window and con colors name tags option for npcs.  A bit new to everything

**Review by adonislive — COMMENTED** [review]
I'm not sure how to add the ui_options.cpp changes for a checkbox for the two Namepate color and Nameplate con color options in this commit.  Will add separately

**Comment by adonislive** [comment]
Ok should be ok all still same commit.  Let me know if I missed anything or made any mistakes  The UI stuff is not something i have as much confidence in yet

**Pull request merged**
